version: '3'
services:
  jupyter:
    restart: always
    container_name: slda-jupyter
    image: private-topic-model-tensor-methods_server
    command: >
      bash -c "python manage.py makemigrations && python manage.py migrate && /tini --
      python manage.py shell_plus --notebook"
    ports:
      - 8866:8866
    depends_on:
      - postgres
    volumes:
      - ./:/code
    working_dir: /code/experiments
  server:
    restart: always
    container_name: slda-server
    build:
      context: .
    command: sleep infinity
    volumes:
      - ./:/code
    depends_on:
      - postgres
  postgres:
    restart: always
    image: postgres
    volumes:
      - database-data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=prod
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=lda
    ports:
      - 6666:6666
volumes:
  database-data:
